src/linux/xorg.rs

`XImage` pointer was not being released at the end of the function.
I've found the following function which seems to have solved the issue:
https://tronche.com/gui/x/xlib/utilities/XDestroyImage.html
The following test script was used. It does not keep consuming memory anymore, so I think the issue is solved.
https://gist.github.com/mdacach/3ccc93751af3ee125739b2f994b85e03
P.S. I've found a simple `XFree(data as *mut _)` to also solve the issue, which I don't fully understand because the image pointer would still leak, I think.

fix: Fix memory leak issue in screen.capture() [Linux]

---

Cargo.toml
src/win32.rs

Changed from sfhash to fxhash because of license issue.
sfhash has LGPL license which conflicts with the Apache-2.0 license
It is depended on the PR I did in display-info. https://github.com/nashaofu/display-info/pull/14

Change from sfhash to fxhash 

---

Cargo.toml
src/linux/wayland_screenshot.rs

In Linux, when taking a screenshot through dbus, if the path contains Chinese characters, it will be percent-encoded like this:
If left untreated, it will cause the program to panic.
So it needs to be decoded:

fix: Panic caused by Chinese characters in file paths

---

Cargo.toml
src/linux/wayland_screenshot.rs

Use [libwayshot](https://crates.io/crates/libwayshot) to get a screenshot using the wlroots protocol. This is required for the library to work on [sway](https://swaywm.org/) for example.
Currently it only tries it if all other methods fail, but it could be possible to detect if wlroots is being used and therefore try it first.

support wlroots based compositors

---

src/darwin.rs
src/image_utils.rs

Captures were really slow for me on macOS(>1s) for a full-screen capture.
cargo-flamegraph showed that most of the time was being spent in `bgra_to_rgba_image` and `remove_extra_data` because they were spending time extending the buffer as items were being added.  I have made changes so that buffers being returned are pre-allocated.
Before:
After:

Improve capture performance on macOS

---

Cargo.toml
src/macos/impl_window.rs

fix: fix Window::all() panic in macos

---

.github/workflows/ci.yaml
Cargo.toml
examples/monitor_capture.rs
examples/window_capture.rs
src/linux/impl_monitor.rs
src/linux/impl_window.rs
src/macos/impl_monitor.rs
src/macos/impl_window.rs
src/windows/boxed.rs
src/windows/impl_monitor.rs
src/windows/impl_window.rs
src/windows/utils.rs

* fix: the overall failure problem caused by an error in the Monitor:all or Window::all #118 
* style: fix cargo fmt and cargo clippy

fix: Monitor:all or Window::all panic

---

.devcontainer/devcontainer.json
Cargo.toml
examples/window_record.rs
src/linux/impl_window.rs
src/macos/boxed.rs
src/macos/impl_window.rs
src/macos/mod.rs
src/window.rs
src/windows/impl_window.rs

* fix: 修复 macos 内存泄漏 #148 
* feat: window添加refresh API

feat: window添加refresh API

---

Cargo.toml
src/linux/wayland_capture.rs

This PR fixes two issues I had encountered with `xcap`.
1. Due to a bug in `xcap`, taking[ more than one screenshoot at a time ](https://github.com/nashaofu/xcap/issues/155#issue-2564845225)would cause XCapError("Screenshot failed or canceled"). 
This was caused by dbus messages getting lost when multiple threads interacted with dbus.
This  seems like a multi-threading bug, probably caused either by improper `dbus` usage. 
This PR fixes this issue, by ensuring no more than 2 threads can take a screenshot at any given time, using a `Mutex`.
I have also included a test, which demonstrates the original bug, and allows for checking if it has returned.
2. Segfaults in `libdbus`. 
For unclear reasons(I am still trying to figure them out with the maintainer[ of  the`dbus` …

Wayland : Fix multithreading bug + fix segfault in libdubs on certain systems.

---

examples/window.rs
src/linux/impl_window.rs
src/macos/impl_window.rs
src/window.rs
src/windows/impl_window.rs

disclaimer: did only test on macos so need some testers
`cargo run --example window`
#171
need to update code for windows/linux
basically i check if the mouse is in the window

feat: window focus

---

Cargo.toml
src/windows/utils.rs

只有window用到了判断系统版本，没必要导入sysinfo这个库，编译后可以减少大概600kb的体积

使用window注册表替换sysinfo

---

Cargo.toml

添加image默认依赖为可选features，默认只开启png格式的编译后可以减少大概6M的体积，如果想开启全部可以使用default-image特性

添加image默认依赖为可选features

---

Cargo.toml
src/windows/boxed.rs
src/windows/impl_monitor.rs

feat: windows支持hidpi

---

examples/focused_window.rs
src/linux/impl_window.rs
src/macos/impl_window.rs
src/window.rs
src/windows/impl_window.rs

closes #190
- **feat: write example to test against**
- **feat: use `activeApplication` to get focused app**

fix: get `is_focused` value dynamically

---

Cargo.toml
src/windows/capture.rs

fix: avoid error log when `DeleteObject` succeeds

---

src/linux/impl_monitor.rs
src/linux/impl_video_recorder.rs

- Update ImplVideoRecorder::new() to accept an ImplMonitor instance.
- Spawn a thread at on_frame() to keep capturing frames using monitor.capture_image().
- Use a RecorderWaker to signal when to wake the recording thread.
- Implement start() and stop() functionality to control the recording state.

feat(linux): implement screen recorder

---

Cargo.toml
src/error.rs
src/linux/wayland_capture.rs

This allows the library to take screenshots on wayland compositors using wlroots such as Sway
Closes #198

feat(wayland): support image capture on `wlroot` wayland

---

Cargo.toml
src/linux/impl_monitor.rs
src/linux/wayland_capture.rs

Wayland didn't have proper scaling support, as the current implementation `get_scale_factor` only worked for x11.
Using the git release of [libwayshot](https://github.com/waycrate/wayshot/tree/main/libwayshot)
we can get logical and physical sizing of the monitors and calculate the scaling.
I've only tested it by setting my scaling factor on `sway` to not 1:
```
[src/linux/impl_monitor.rs:233:9] scale_factor = 1.2
```

fix(linux): add Wayland scaling and update libwayshot

---

src/windows/impl_window.rs

Fixes #228. 
As far as I understand, it should be safe to transfer or share HWND across threads, given how HWND is used in this project.
Related: microsoft/windows-rs#3399

Implement Send and Sync for ImplWidow of Windows

---

Cargo.toml

In my project there was a different library that was using objc2 0.3.0 which caused me to experience errors on MacOS with certain functions not being present. Please find more information about the error attached in the next comment.
So I froze the objc2 and related package versions to 0.3.1 as xcap does not work under 0.3.0 on MacOS.

fix: bump objc2 versions to 0.3.1 or higher to prevent conflicts with 0.3.0 on MacOS

---

src/linux/wayland_capture.rs
src/linux/wayland_video_recorder.rs

I have not worked with `zbus` before, but this seems correct.
I can't not attribute this to being some NixOS quirk, but it seems like using `DeserializeDict` should be the default as per [the `zvariant` docs](https://docs.rs/zvariant/latest/zvariant/derive.DeserializeDict.html#alternative-approaches), given the code in `ScreenCastStartResponse`, `ScreenCastStartStream` and `ScreenshotResponse` does not have the noted `#[serde(with = "as_value...")]` entries, so I assume this was the intended way it should be done.
I have tested screen recording on wayland to work after this fix.
Fixes #235

fix: Use DesereializeDict for "signature = dict" structs

---

src/linux/wayland_video_recorder.rs

As it currently stands, a paused `WaylandVideoRecorder` will use up its allocated "buffers" by returning from `process()` without [queuing the buffers back](https://docs.pipewire.org/page_streams.html#ssec_consume). This makes it stop issuing calls to `process` entirely which makes the thread get stuck and unable to resume with a later call to `start()`.
In `pipewire-rs` this is handled automatically when calling `dequeue_buffer()` since the returned `Buffer` automatically handles this in its [`Drop`](https://gitlab.freedesktop.org/pipewire/pipewire-rs/-/blob/main/pipewire/src/buffer.rs#L46-52) implementation.
I assumed that the intended behaviour of start/stop is to pause/resume rather than fully disassemble and reassemble the recording stack on each call.
Refs:
- …

fix: Prevent buffers from being wasted on a paused wayland recorder
